/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CeasarsCoding;

public class App {
    public static String encrypt(String message, int shift){
        String trial = "";
        for (int i = 0; i < message.length(); i++){
            trial += (char)(message.charAt(i) + shift);
        }
        return trial;
    }

    public static String decrypt(String message, int shift){
        String trial = "";
        for (int i = 0; i < message.length(); i++){
            trial += (char)(message.charAt(i) - shift);
        }
        return trial;
    }
}
