/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CeasarsCoding;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testEncryptWithShift1() {
        App classUnderTest = new App();

        int shift = 1;
        String message = "Hello World";
        String expectedResultMessage = "Ifmm Xpsme";
        String actualResultMessage = CeasarCipher.encrypt(shift, message);

        assertEquals(expectedResultMessage, actualResultMessage);
        
    }

    //tests encryption of a message with shift of 6

    @Test public void testEncryptWithShift6() {
        App classUnderTest = new App();

        int shift = 6;
        String message = "Hello World";
        String expectedResultMessage = "Nkrru Cuxrj";
        String actualResultMessage = CeasarCipher.encrypt(shift, message);

        assertEquals(expectedResultMessage, actualResultMessage);

    }

    //tests encryption of a message with a shift of 10

    @Test public void testEncryptWithShift10() {
        App classUnderTest = new App();

        int shift = 10;
        String message = "Hello World";
        String expectedResultMessage = "Rovvy Gybvn";
        String actualResultMessage = CeasarCipher.encrypt(shift, message);

        assertEquals(expectedResultMessage, actualResultMessage);

    }

    //tests decryption of a message with a shit of 1

    @Test public void testDecryptWithShift1() {
        App classUnderTest = new App();

        int shift = 1;
        String message = "Ifmm Xpsme";
        String expectedResultMessage = "Hello World";
        String actualResultMessage = CeasarCipher.decrypt(shift, message);

        assertEquals(expectedResultMessage, actualResultMessage);

    }

    //tests decryption of a message with a shift of 6

    @Test public void testDecryptWithShift6() {
        App classUnderTest = new App();

        int shift = 6;
        String message = "Nkrru Cuxrj";
        String expectedResultMessage = "Hello World";
        String actualResultMessage = CeasarCipher.decrypt(shift, message);

        assertEquals(expectedResultMessage, actualResultMessage);

    }
}
