/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CeasarsCoding;

import java.util.Scanner;

public class App {

    public static void main(String[] args){
        Scanner text = new Scanner(System.in);

        System.out.print("Enter message you wish to be encrypted");

        String msg = text.nextLine().trim().toLowerCase();

        System.out.print("Input String : " + msg);

        System.out.print("Encrypted String : " + Encrypt.encrypt(msg, 24));

        System.out.print("Decrypted String : " + Decrypt.decrypt(Encrypt.encrypt(msg, 24),24));
    }
}
